### ISSUE TITLE
 Add Typical User writable data path #68 

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/development#12]
https://github.com/OpenCPN/OpenCPN/issues/2266

**Comment by leamas** [comment]
Isn't this a duplicate of #23?

**Comment by rgleason** [comment]
It is asking to show the typical user writeable path for each os.

**Comment by leamas** [comment]
Any  reasonable solution on #23 would include this. IIRC, it's by the way already in the installer docs.
I still suggest we close it, there is already remarsks in #23 since we have talked about it.

**Comment by rgleason** [comment]
Ok, it is just that plugin devs have in their head the paths for their OS generally, but not for others, and they need them to fix stuff.  We need this info front and center somewhere, if it is a short description and link to your improved and well crafted docs, fine!. 

Closing
