### ISSUE TITLE
 Flatpak local builds #69 

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/development#13]
https://github.com/OpenCPN/OpenCPN/pull/2303#issuecomment-860141498

**Comment by leamas** [comment]
That is, flatpak build of core OpenCPN.

**Comment by leamas** [comment]
... which is doumented in https://opencpn-manuals.github.io/development/ocpn-dev-manual/5.3.1/od-compile-linux.html#_flatpak. 

Which boils down to that this is fixed, and bug could be closed. Or?
