### ISSUE TITLE
 Discussion - O Distribution Strategy #70 

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/development#14]
https://github.com/OpenCPN/OpenCPN/discussions/2251#discussioncomment-828368

**Comment by leamas** [comment]
And? What are the consequences, if any, for the Development Manual? That we should document how OpenCPMN is distributed?

**Comment by rgleason** [comment]
I do not know why I thought something in this discussion should be included in the dev manual. Lwt me think about it.

**Comment by rgleason** [comment]
I think this should be closed. I checked it.
