### ISSUE TITLE
 Author's Manual commit process (right now) #81 

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/development#17]
https://github.com/opencpn-manuals/plugins/issues/4#issuecomment-895372062

**Comment by leamas** [comment]
I actually think we should close this, and file bugs against the main project about INSTALL.adoc and WORKFLOW.adoc.

Thoughts+

**Comment by rgleason** [comment]
Yes. Sure. Will you dp it please?

**Comment by leamas** [comment]
done
