### ISSUE TITLE
 author commits #82 

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/development#18]
https://github.com/opencpn-manuals/plugins/issues/4#issuecomment-895372062

Alec wrote

Remember: casual editing will be simple. What we are working with now is central workflows. They are slowly stabilizing, but we are not there.

We have one branch we need to know which is build. When we push anything on it, it will trigger a complete build of the website (and nowadays also some checks). The gh-pages branch is sort of reserved, we just should not touch it, and there is no need to update it.

Besides this, all is standard git workflow, a standard which is non-existing. That is, git is flexible and we are in the process of finding out how to use it.

But I will not talk more about this here, it's the wrong repo...

**Comment by leamas** [comment]
Now when we have at last the very first versions of WORKFLOWS.adoc available: Can we close this? Or did you have something else in mind?

We'll certainly need some simple instructions for casual, drive-by fixes. But that's something else, I guess (?)

**Comment by rgleason** [comment]
I have not kept track of the changes completely, and I am still all thumbs with this system, but yes I think we can close this
