### ISSUE TITLE
 Testplugin Asciidoc/Antora Editing #436 

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/development#20]
Where & How should this be done now?

(Alec you probably don't want us to be doing anything just yet)
Let us know when you are ready please.

**Comment by leamas** [comment]
This is about rebuilding the Plugins Manual, right? The first outlines to docs are in https://github.com/opencpn-manuals/main, the file WORKFLOWS.adoc and INSTALL.adoc. Please file feedback as bugs on the main project, my idea is to avoid duplication, at least until things are more stable

**Comment by leamas** [comment]
We now have a working process to rebuild the complete Plugins Manual. I suggest that you test it (the process is documented in INSTALL.md, it's the same as for development). If you think things seems to work we should invite Jon so he also can make commits and trigger builds.

**Comment by rgleason** [comment]
Ok, 

I have a new repository   rgleason/development which seems to be working. I would like to make a PR to opencpn-manuals/development.  May I?

To do this now, I should fork all of opencpn-manuals then clone it locally?  Isn't that a big chunk?
(We're getting new laptops after 12 years, due next week, but I don't want to choke up this one)

Then I make some small changes, git add, git commit, git push the make the PR?

I thought we would just use the individual source plugins like these
https://github.com/rgleason/LogbookKonni_pi/tree/master/manual/logbook/modules
https://github.com/rgleason/weather_routing_pi/tree/master/manual/weather_routing

What is the right way to do it?

**Comment by leamas** [comment]
on phone  being terse. 

There is no need tp clone amything on github  no need to make a rgleason/dedevelopment. Just make a local clone of opencpn'manuals/development  , edit, commitand push. You have full commit rights. Details in WORKFLOWS

**Comment by rgleason** [comment]
Oh, I forked and cloned, now changes are in rgleason/ dwvelopment.

**Comment by leamas** [comment]
... but you havn't pushed them. This become messy, we now need to fix so we get your changes in place before we can start to clean up your environment. Do like this ion your local clone of rgleason/development:

    $ git remote add upstream  git@github.com:opencpn-manuals/development.git
    $ git remote update upstream
    $ git rebase upstream/main
    $ git push upstream main

You might get some conflicts when doing  _git rebase_. If  you can resolve them, fine. If not:

    $ git rebase --abort
    $ git push origin main:main

And report back, I will then hopefully be able to merge your changes.

This is needlessly complicated since you forked at github. We will clean up and simplify later. For now, the focus is to get your changes merged

**Comment by leamas** [comment]
ping? any progress on this?  we need to merge your changes before it's too complicated...

**Comment by rgleason** [comment]
Done

```
> Rick@Dart MINGW64 ~/documents/github/development (main)
> $ git remote -v
> origin  git@github.com:rgleason/development.git (fetch)
> origin  git@github.com:rgleason/development.git (push)
> 
> Rick@Dart MINGW64 ~/documents/github/development (main)
> $ git remote add upstream git@github.com:opencpn-manuals/development.git
> 
> Rick@Dart MINGW64 ~/documents/github/development (main)
> $ git remote -v
> origin  git@github.com:rgleason/development.git (fetch)
> origin  git@github.com:rgleason/development.git (push)
> upstream        git@github.com:opencpn-manuals/development.git (fetch)
> upstream        git@github.com:opencpn-manuals/development.git (push)
> 
> Rick@Dart MINGW64 ~/documents/github/development (main)
> $ git remote update upstream
> Fetching upstream
> Enter passphrase for key '/c/Users/Rick/.ssh/id_ed25519':
> remote: Enumerating objects: 230, done.
> remote: Counting objects: 100% (225/225), done.
> remote: Compressing objects: 100% (35/35), done.
> remote: Total 230 (delta 187), reused 217 (delta 182), pack-reused 5 eceiving objects:  74% (171/230)
> Receiving objects: 100% (230/230), 267.70 KiB | 1.80 MiB/s, done.
> Resolving deltas: 100% (187/187), completed with 37 local objects.
> From github.com:opencpn-manuals/development
>  * [new branch]      build      -> upstream/build
>  * [new branch]      foo        -> upstream/foo
>  * [new branch]      gh-pages   -> upstream/gh-pages
>  * [new branch]      main       -> upstream/main
> 
> Rick@Dart MINGW64 ~/documents/github/development (main)
> $ git rebase upstream/main
> Successfully rebased and updated refs/heads/main.
> 
> Rick@Dart MINGW64 ~/documents/github/development (main)
> $ git push upstream main
> Enter passphrase for key '/c/Users/Rick/.ssh/id_ed25519':
> Enumerating objects: 23, done.
> Counting objects: 100% (23/23), done.
> Delta compression using up to 8 threads
> Compressing objects: 100% (11/11), done.
> Writing objects: 100% (12/12), 1.22 KiB | 1.22 MiB/s, done.
> Total 12 (delta 10), reused 0 (delta 0), pack-reused 0
> remote: Resolving deltas: 100% (10/10), completed with 9 local objects.
> To github.com:opencpn-manuals/development.git
>    758afdb..b6a7119  main -> main
> 
```

**Comment by leamas** [comment]
OK, it was right to close this one. But let's hijack it for some cleanup actions.

First, I suggest that you completely removes the rgleason/development repo at github. It just don't have  any purpose.

Secondly, on your local machine I suggest that you clean up your remotes, like this:

    $ git remote remove origin
    $ git remote rename upstream origin

From this point you should be able to make simple changes by editing files, commit and push.  Don't forget to check the details in the WORKFLOWS document.

**Comment by leamas** [comment]
Have you been able to make a local build?

**Comment by rgleason** [comment]
Did the cleanup you suggested.

```
Rick@Dart MINGW64 ~/documents/github/development (main)
$ git remote -v
origin  git@github.com:opencpn-manuals/development.git (fetch)
origin  git@github.com:opencpn-manuals/development.git (push)

```

### Development Manual for Authors
https://github.com/opencpn-manuals/development/blob/main/WORKFLOWS.adoc
https://github.com/opencpn-manuals/development/blob/main/INSTALL.adoc
- Work from a local clone of  https://github.com/opencpn-manuals/development/

### Plugin Manuals for Authors
https://github.com/opencpn-manuals/plugins/blob/main/WORKFLOWS.adoc
https://github.com/opencpn-manuals/plugins/blob/main/INSTALL.adoc
- Work from a local clone of

**Comment by rgleason** [comment]
Would it be helpful or confusing if the links above were inserted into
https://github.com/opencpn-manuals/main/blob/main/INSTALL.md
OR
https://github.com/opencpn-manuals/main/blob/main/README.md

**Comment by leamas** [comment]
> Would it be helpful or confusing if the links above were inserted into

Probably confusing. These documents are about building the manual, we must not assume that it exists  here, I guess.

**Comment by leamas** [comment]
Back to basics. Have you been able to do a local build?

**Comment by rgleason** [comment]
Ok,  thanks for asking.
I did a local build  
https://github.com/opencpn-manuals/main/blob/main/INSTALL.md#local-builds

and it completed.  What next?

**Comment by leamas** [comment]
crash course: Find a typo in the manual (I'm sure you can), and make a small commit which fixes it. Then follow the procedures in WORKFLOW to first make a test build and then commit to main branch and push.

**Comment by leamas** [comment]
Ah, forgot: You can preview the result by pointing firefox to docs\index.html

**Comment by rgleason** [comment]
https://github.com/opencpn-manuals/development/blob/main/WORKFLOWS.adoc#basic-minor-change

1. Edited the Testplugin Manual under "Development Setup"  first line.
`This entire page needs work and revision. 1. EDIT DOWN 2. ELIM DUPS 3. MOVE CONTENT
`
Then git add the change and commit.
Then push up to  opencpn-manuals/development
Then check  https://opencpn-manuals.github.io/development/ocpn-dev-manual/5.3.1/intro-AboutThisManual.html
In a short while the change appears https://opencpn-manuals.github.io/development/ocpn-dev-manual/5.3.1/pm-overview-prereq-other.html
Then at the bash prompt do
`antora site.yml`
and browse to your local docs folder.

**Comment by rgleason** [comment]
Thanks. I think I've got the development process now.

For editing plugins now, where do we start?

**Comment by leamas** [comment]
I was actually thinking in other terms. Could you possibly take care of #15? I have never really used this stuff... Just write a single page describing how to use it. My plan is to make make an plugin development overview page which can link to it later.

Also, need your help with remaining problems in #3. Could you possibly look also into this?

**Comment by rgleason** [comment]
#15 Sure l woild be happy to make such a page.
#3 Yes I can work on link errors and read each page and check on relevancy.

**Comment by leamas** [comment]
@rgleason 

OK, I have filed notes in #15 and #3.

Back to git crash course (the problems you have are 90% git-related as I see it). Noted that you have to enter a password to make a push. This is not that convenient, and actually less secure than the normal method which uses ssh keys. To use this, work in git bash and create your own keys (private and public) with

    $ ssh-keygen

The command will ask you some questions, just hit return to use the default values. When completed, do

    $ cat $HOME/.ssh/id_rsa.pub

This will output something like
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCuGZxLPI66ujL8q1CCZAQgEBA0u5nfHiyBgpiyPUrPnQ8nPtMvVcFe1flykw0liJqFQTRnU07VkjOcw86WyuZl+zwm7HL2vQBbz3XAZJsJBdaU6QpIaJdVZz1/AF3KPPNVnrm4CUscOfjvKzLWGHvA6CgRFWC4IPEcOvTEZQNV+HwpghDh7qGJrLIlrkNUHElg+BxIaynM2Pa3KHNcqoGN4TYG2ThTm76XqYtU9pw7yLp4+k2uYFj1skg37Y6BXAbz3FbBikfEk3JwV/Su9CPunGDbESkgc6bUbtmw/AlJ3/qbRtc89/naETbJzfbpY3HsI6RXTW3h1e/CPT7CkaJkNzn51qXRqsEtIu7kCf3i3cfxZXxkdS8zCwzbC2HaSpXAlemjQKAswfTryH2q/9Fy6e8YCS6rdBsIbLVIqMQxdTlmIwqGwXKiZS22Mm31BqNjY1klpFwz3F9PH/PIhieE19ZpKOBIzZio4jwjT6pamDGyxiFyMPU/xLbtdrbzy0k= al@hemulen.nowhere.net

```
Copy the whole thing using the mouse and the context menu (*Not* ctrl-C!). Then go to your _Github account | Settings | SSH and GPG keys_  and push the _New SSH key_ green button top-right. Give it some title, paste into the main area and push the _Add SSH Key_  button.

That's it. Next time you push there will be no prompt for a password. Be aware that $HOME/.ssh/id_rsa is a secret you need to be careful with.

@rasbats: Applies to you as well unless, which I suspect, already have this setup.

**Comment by rgleason** [comment]
Thanks Alec I had followed the SSH instructions on Github and made a separate ssh key that required a Pass Phrase and then was going to gradually change from https login to an ssh login for all the github plugins
`git@github.com:opencpn-manuals/development.git
`
This was working, but it is a pain to have to enter the pass phrase.  I do have this key previously, so I did not over write it, but have added it to my account.   I hope this works more seamlessly.

**Comment by leamas** [comment]
I told you: Enter return on all questions. This included the passphrase question which also should be empty.

My suggestion: Remove the two files $HOME/.ssh/id_rsa and $HOME/.ssh/id_rsa.pub. Run ssh-keygen again, this time: enter return on all questions. That is, all of them.

Then register the new key on github like above (you can remove the old if you like, bit it doesnt really matter -- it became useless when you removed you old private key).

**Comment by rgleason** [comment]
I had used this to create a new ssh key with pass phrase
https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#adding-your-ssh-key-to-the-ssh-agent

Then I added my existing  id_rsa  without a pass phrase.

Ok Alec I can do that, but what if I have used that key for other things?
(I have since long forgotten?)

Incidentally, the way to change the logins from a pwd login to ssh login is to use
https://docs.github.com/en/get-started/getting-started-with-git/managing-remote-repositories#changing-a-remote-repositorys-url

`git remote set-url
$ git remote set-url origin git@github.com:USERNAME/REPOSITORY.git     <--for SSH
$ git remote set-url origin https://github.com/USERNAME/REPOSITORY.git  <---for HTTPS
$git remote -v   <---to check
`
https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh/checking-for-existing-ssh-keys

**Comment by leamas** [comment]
Why do you google stuff when I have simple instructions in this issue? Everything you neede to do was described [above](https://github.com/opencpn-manuals/development/issues/20#issuecomment-899320053) "Confused"

> Incidentally, the way to change the logins from a pwd login to ssh login is to use

Sort of, but that link is the other way around: It describes how to change from ssh to https. You don't want to do that. That said, I  forgot that part. What you need to do is something like

    $git remote set-url git@github.com:opencpn-manuals/development.git

unless it's not already set. It will not hurt in any case, though. The git@ url is as copied from the github repo, the green Code button,  the SSH alternative

**Comment by leamas** [comment]
Next time you clone a repo on github: Use the ssh link instead of the https to avoid the set-url hassles.

**Comment by leamas** [comment]
Off for  an hour or so...

**Comment by rgleason** [comment]
I changed remote on my local polar_pi using
documents/github/polar_pi (master-update)
`$ git remote set-url origin git@github.com:rgleason/polar_pi.git
`
and  then pushed a commit and it works now.

I did not want to delete my existing rsa_id because it may be used by other services.

**Comment by rgleason** [comment]
Good point "Next time clone a repo on github: Use the ssh link instead of the https to avoid the set-url hassles."
I will, but I have many plugins setup currently for https, so I will be using a lot of:
`$ git remote set-url origin git@github.com:rgleason/<pluginname_pi>.git `

**Comment by leamas** [comment]
You just created it, how could it be used by other services? 

If in doubt, rename it and see if anything breaks...

**Comment by rgleason** [comment]
```
You just created it, how could it be used by other services?
If in doubt, rename it and see if anything breaks...
```

No, I have had my existing id_rsa  for many years.... maybe 10-12 years.  I would not necessarily know if I had broken something.
Particularly with some backup services and website management services.

**Comment by rgleason** [comment]
Alec   Yes, I like that.   [Everything you need to do was described above ](https://github.com/opencpn-manuals/development/issues/20#issuecomment-899320053)

**Comment by leamas** [comment]
> No, I have had my existing id_rsa for many years

OK, that explains a little part of this mess.
