### ISSUE TITLE
Circleci: Access to log files and other files from the build. #72 #437

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/development#21]
Aaron (CircleCI) wrote Jun 8, 2021, 21:27 EDT

Hi,Thank you for contacting CircleCI Support!One way to accomplish this currently is to make use of artifacts. https://circleci.com/docs/2.0/artifacts/#uploading-artifacts

You can specify the store_artifacts key in your config.yml file, and a path for files to be uploaded to CircleCI. These files would then be available for viewing in the Artifacts tab of the job details page.In your case, you could set the following to upload the error logs:

store_artifacts: path: /home/circleci/project/build/CMakeFiles/CMakeOutput.log
store_artifacts: path: /home/circleci/project/build/CMakeFiles/CMakeError.log

Another workaround would be to output the content of the error logs directly. This could be done with commands like:

run: cat /home/circleci/project/build/CMakeFiles/CMakeOutput.log
run: cat /home/circleci/project/build/CMakeFiles/CMakeError.log

This would require manually specifying the file paths for the files to be uploaded, but you are more than welcome to create a feature request on the following page if the above solution does not work for your use case:
https://circleci.canny.io/cloud-feature-requests

Please let me know if you have any additional questions, or if you would like me to clarify anything!Best Regards

**Comment by leamas** [comment]
This is ideas to consider in the plugin workflows. However, I don't that is related to the documentation since it isn't implemented. 

Thoughts?

**Comment by rgleason** [comment]
This is information to help debugging.
How to gain access to log files that are in each build. It should be put somewhere.

**Comment by leamas** [comment]
But then again, this is not a documentation problem, it involves changes in the code. Which means that it should be filed against shipdriver and testplugin, right?

**Comment by rgleason** [comment]
Yes, but it applies for both. It is just a debugging technique.

**Comment by leamas** [comment]
This is partly about how the shipdriver/testplugin templates are configured, and that question belongs there. The other question is how to use cloudsmith, which is about the cloudsmith docs.

I you think you could write up something relevant here, please do. I don't see how it would be possible right now. We need a use-case and an implemented, tested solution before documenting in our own manual.
