### ISSUE TITLE
Manual: Add plugin dependencies or link  

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/development#22]
Add to manual?
https://github.com/OpenCPN/plugins#dependencies

**Comment by leamas** [comment]
Ack: We should ensure there is a link (*not* duplicate, it's too hard to maintain).

**Comment by rgleason** [comment]
What?

**Comment by leamas** [comment]
We  should add a link to existing documentaion about plugin dependencies. But not duplicate this info somewhere else,  too hard to maintain

**Comment by rgleason** [comment]
Yes

**Comment by leamas** [comment]
Is  12a19bc7  i. e., https://opencpn-manuals.github.io/development/ocpn-dev-manual/5.3.1/plugin-devel-overview.html#_catalog  good enough to close this issue?

**Comment by rgleason** [comment]
I don't care anymore.

**Comment by leamas** [comment]
Well, you can add things yourself. I probably did not understand what you meant here.
