### ISSUE TITLE
 feature request: iENC and ENC cells for ECDIS testing

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/development#25]
OpenCPN/OpenCPN#2318

**Comment by leamas** [comment]
This is a core OpenCPN  RFE , certainly not implemented. How does this relate to what to document?

**Comment by rgleason** [comment]
See https://github.com/OpenCPN/OpenCPN/issues/2318#issuecomment-877636539

**Comment by leamas** [comment]
Ah, right. Makes sense.

**Comment by leamas** [comment]
Added as an resource in #25, peek preview [here](https://opencpn-manuals.github.io/development/ocpn-dev-manual/5.3.1/ECDIS_testdata.html)

OK to close with this commit in place?
