### ISSUE TITLE
Where to store the plugin documentation guidelines

### ISSUE THREAD

**Issue by leamas** [opencpn-manuals/development#28]
Currently we have the plugin documentation guidelines in the development manual: https://opencpn-manuals.github.io/development/ocpn-dev-manual/5.3.1/pm-plugin-documentation.html

However, here is also the plugin authoring onfo: https://opencpn-manuals.github.io/plugins/opencpn-plugins/0.1/authoring/author.html

Clearly, these are related, the stuff should be on one place, linked in the other.

For dependency reasons, I think it would be better with a link development -> plugins i. e., that this chapter basically should live in the Plugins manual, with a link in the development manual

@Rasbats @rgleason Thoughts?

**Comment by Rasbats** [comment]
Agree.

**Comment by rgleason** [comment]
I agree  live in plugins

**Comment by leamas** [comment]
OK, we all agree. I'm about to copy the files to plugins. However, I don't to rock the boat here until we have resolved issues in #20

**Comment by leamas** [comment]
Copied files to plugins in https://github.com/opencpn-manuals/plugins/commit/7a0db26e8bcb5a807e19334e55bcc5ade142eb28

**Comment by rgleason** [comment]
Close?

**Comment by leamas** [comment]
Not yet, need to remove from here and add a link first. Will take some time, much to do and I also need to make a new overview page for plugin development, I think.

**Comment by leamas** [comment]
Fixed in 7cb61e6. Closing
