### ISSUE TITLE
Dropping the Attic

### ISSUE THREAD

**Issue by leamas** [opencpn-manuals/development#29]
Is it time to drop the Attic? 

Personally, I think it's about time to avoid spending time on these antiquated docs. But then again, that's me.

Also: "dropping" here means that we remove it from the git tip. Everything will still be available in the git history, nothing is lost in case it's actually required.

**Comment by rgleason** [comment]
Yes, remove them,  but be sure that there are no pages being used from there in the new docs, please.
I tried to rename the pages that are being used to make it clearer and change the links, but I may not have gotten all of them.
There are some others that can be removed too.

**Comment by leamas** [comment]
Well, we are doing link checks, they will flag whatever problems there are. Will do.

Important now is #20, but please report back there when you have time.

**Comment by rgleason** [comment]
Thanks give me 30 min

**Comment by leamas** [comment]
You have all time :)

**Comment by rgleason** [comment]
Done, thanks. We can drop the attic.

**Comment by leamas** [comment]
Attic is dropped. Closing
