### ISSUE TITLE
Link errors. 

### ISSUE THREAD

**Issue by leamas** [opencpn-manuals/development#3]
The logs from checklink (that is, from [full-linkcheck]) reveals that external links have been lost. One example is the links to the shipdriver manual, there  might be more.

**Comment by leamas** [comment]
@rasbats: Somewhere in the git jungle I think we have an Antora version of the Managed Plugins wiki (?)  Can you find it anywhere?

**Comment by Rasbats** [comment]
[https://github.com/Rasbats/managed_plugins/tree/asciidoc/manual](https://github.com/Rasbats/managed_plugins/tree/asciidoc/manual)

**Comment by leamas** [comment]
thanks, found it late yesterday. My memory is excellent, but short...

**Comment by leamas** [comment]
I'm working with the broken links. However, a bunch of them seem related to the windows stuff and needs to be fixed by @rgleason, I don't have enough windows context.

**Comment by leamas** [comment]
@rgleason: When looking at the output from the full linkcheck, please disregagard any `  Code: 403 Forbidden` errors. Will try to hide them, they are not relevant.

Also disregard this, which is reported for every page, and I don't see any remedy:
```
https://opencpn-manuals.github.io/development
-> https://opencpn-manuals.github.io/development/	
  Line: 17
  Code: 301 -> 200 OK
 To do: The link is missing a trailing slash, and caused a redirect. Adding
	the trailing slash would speed up browsing.
```

**Comment by rgleason** [comment]
You are checking development links.
You want me to fix some windows related links.

I am to clone development repos and run linkchecker?

**Comment by leamas** [comment]
> I am to clone development repos 

Yes, clone this repo (don't forget to consult WORKFLOWS for the process.

> and run linkchecker?

No. You can see the results under the Action button, last build is [here](https://github.com/opencpn-manuals/development/runs/3321527481?check_suite_focus=true), look into the full-linkcheck section.

When done: commit, rebase and push to the _build_ branch (see WORKFLOWS). Don't forget to add `[full-linkcheck]`to the commit message so that all checks are run.

**Comment by rgleason** [comment]
Under  :build the site with antora"   Full LInkcheck 
I see a number of missing links. 
There are a lot of links to cruiser's forum which still work.
I am trying to find the locations in the text for these.  
How would one do that?

**Comment by leamas** [comment]
They are straigt html link, right? Just do `git grep :https://www.cruisersforum.com/`, that gives you the matches and files. Or use `git grep -l`which just returns a list f files containing the link.

**Comment by rgleason** [comment]
Tried

Rick@Dart MINGW64 ~/documents/github/development/modules/ROOT/pages (main)
$ grep :https://www.cruisersforum.com/
and cursor is just blinking.

This is using Windows Bash prompt.

**Comment by leamas** [comment]
grep reads by default from stdin... type control-C to get out this. Then use the correct command `git grep` which by default searches from current dir.

**Comment by leamas** [comment]
@rgleason:

I have fixed the full-checklink script and it gives IMHO now reasonable results. Also updated main branch.

Furthermore, I have fixed llinks which I think belong to me. The exception are som xrefs with a plugin-installer: prefix. These are on me,  they belong to the plugin installer docs.

I'm not really qualified to fix the rest; it would be great if you could handle them. Please report back if you consider any message a false positive, I have finally been able to squelch various sites (you could look in ci/w3c-linkcheck.sh), so in such cases we could cuppress such messages.

**Comment by leamas** [comment]
rgleason said: https://github.com/opencpn-manuals/development/issues/27#issuecomment-898880291

Hm... Yes, the link is  does indeed work. I will blacklist cruisersforum.com (done in 6f85a92e) so we don't get this error reported. Again, something with robots.txt, I guess.

That said, when I look at the link there is 13 years old instructions how to compile OpenCPN. These are of course totally useless, the build procedures has undergone massive changes over this time. So, at a closer look, the best cause of action is probably to just drop this link.

**Comment by rgleason** [comment]
Agreed.  We have a lot of cleanup to do too.
Also perhaps it would be simpler to loose some of the old docs provided they aren't being used?

**Comment by leamas** [comment]
> Also perhaps it would be simpler to loose some of the old docs provided they aren't being used?

Definitely.  Better to have something which is correct and actually useful.

**Comment by rgleason** [comment]
Last night I pushed a bunch of link fixes up to my repository. Should I make a PR to development now?

**Comment by leamas** [comment]
well, you could. And then accept it,  you have the powers. But first, rebase it, there has been changes upstream.

I would not make a pr, but instead add  a new remote upstream and push directly
 Too much to tap on phone...

**Comment by rgleason** [comment]
Yes, I think I can do this.

**Comment by leamas** [comment]
@rgleason : I have done what I can here for now. The remaining problems seems, to me, like something you could handle better.

One or two of remaining errors are like xref:AlternativeWorkflow... These are errors in rasbats/managed_plugins, we cannot do anything about them here. Filed a bug at https://github.com/Rasbats/managed_plugins/issues/9

I think we (i. e., you ) just should drop the page on using visual_studio from 2013. It is littered with problems, and I don see the use.  We should probably drop the 2015 page as well, focusing on 2017 which we actually use and recommend. If not, we will have to review the 2015 stuff which might be painful.

**Comment by leamas** [comment]
@rasbats has updated the managed_plugins site; there are no errors from there visible in current logs.

There is just 6-7 files with errors. If you remove the outdated visual Studio 2013 stuff and also drops the community_old page half of the errors are gone. And, as I see it, there is no point working with them anyway, they are not used.

**Comment by rgleason** [comment]
Will do. Have been involved with responding to an erroneous parking study for our neighborhood.

**Comment by rgleason** [comment]
1. Drop the page on using visual_studio from 2013. It is littered with problems
https://opencpn-manuals.github.io/development/ocpn-dev-manual/5.3.1/compile_windows_2013_vs_community.html
https://opencpn-manuals.github.io/development/ocpn-dev-manual/5.3.1/compile_windows_2013_vs_community_ov4.2-4.8.8.html

Are these the two you are asking to delete?  These are good pages for compiling historic versions. I did not author these pages, Rasbats did.  He should do what he thinks is best.

2.  Drop the community_old page so half of the errors are gone. 
I don't know which page you are referring to, can you provide a link?

3. And, as I see it, there is no point working with them anyway, they are not used.
Perhaps no.

How about these pages, should they be removed?
https://opencpn-manuals.github.io/development/ocpn-dev-manual/5.3.1/nsis_installation_directory.html
https://opencpn-manuals.github.io/development/ocpn-dev-manual/5.3.1/nsis_table.html

Comments from Rasbats and Leamas please.

**Comment by Rasbats** [comment]
>Drop the page on using visual_studio from 2013

Please remove. Also 2015.

>How about these pages, should they be removed?

Yes.

**Comment by leamas** [comment]
You two are the windows experts, I have basically nothing to add here besides the general statement that less is more.

Just a heads-up (again): When removing, please also remove the corresponding images.

And: Please don't make this a single, large commit removing all sorts of stuff. Better to remove each file in a separate commits. This way its easier to find in the history.

Also: as soon as anything like this is committed and verified to build, please push to main branch asap. These kind of structural changes often leads to rebasing problems, and these are simpler to resolve if main moves in smaller steps.

**Comment by leamas** [comment]
All links in development manual good. However, still affected by  https://github.com/opencpn-manuals/plugins/issues/6.  Let's make sure it's fixed before closing this issue.

**Comment by leamas** [comment]
Seems that  https://github.com/opencpn-manuals/plugins/issues/6  will take a long time to resolve.  Closing this issue, the broken links in the plugin manual is a plugin manual problem.
