### ISSUE TITLE
Old Manual - delete which pages?

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/development#30]
Which pages should be removed starting with:
https://opencpn-manuals.github.io/development/ocpn-dev-manual/5.3.1/beta_plugins.html

Just vote/comment below
Beta Plugins
CI build push to git
CI Travis encrypption
CI Advanced Debug tips
Learning - various pages. 

@leamas  and @Rasbats

**Comment by Rasbats** [comment]
All!

**Comment by leamas** [comment]
I basically agree with Rasbats. The oplaydo stuff *might* be worth saving, but it might be a nightmare to update. Perhaps better to just remove for now, we can always resurrect it from git if anyone is motivated and have time.

When removing these files, please also remove the corresponding images.

**Comment by leamas** [comment]
@rgleason : Saw your commit basically marking these for removal by patching nav.adoc.

Personally, I don't think we need any more intermediary steps. Since we have agreed on to actually remove them (?), this is IMHO the time to actually do it.

**Comment by leamas** [comment]
@gleason : if you are under way here please take your time. If not I can do it, if you like.  Some feedback would be great.

**Comment by rgleason** [comment]
Alec, sorry, got to go afternoon sail. There is wind.

**Comment by rgleason** [comment]
can you do it?

**Comment by leamas** [comment]
No problem, I'll do it. And don't apologize for sailing!

**Comment by leamas** [comment]
I have removed even more, including the dreaded 2013 and 2015  Visual Studio workflows, old linux workflows and what not.

@rgleason : This also includes some files marked as KEEP , aimed for the user manual. They were blocking #3, and was out of scope anyway. HOWEVER, before I removed them i tagged the sources with the tag _rick-um-keep_ i. e., if you do `git checkout git-um-keep` the files are available again.

With this all link errors originating in the development manual are fixed. However, we have https://github.com/opencpn-manuals/plugins/issues/6 which affects us.

Closing for now. Please re-open if required.

**Comment by rgleason** [comment]
@rgleason : This also includes some files marked as KEEP , aimed for the user manual. They were blocking #3, and was out of scope anyway. HOWEVER, before I removed them i tagged the sources with the tag rick-um-keep i. e., if you do git checkout git-um-keep the files are available again.

Which files please?

**Comment by rgleason** [comment]
The 4 Pages are duplicates of Dokuwiki, Development so they can be deleted.
I have marked those pages in Dokuwiki for possible inclusion in the User Manual
I have also added the new Community Page for possible inclusion in the User Manual.

**Comment by rgleason** [comment]
Thanks for deleting all those pages. Its now all set and ok.
Sail was good 9-12 knots on a good afternoon.

**Comment by leamas** [comment]
> This is why I hate this system. It is far easier for you to unwind this, than me.

When you have been frustrated over "this system" your problem is  git rather than Antora/Asciidoc. 

git *is* a complex beast and takes time to learn and internalize. OTOH, the time you spend on learning git is beneficial not only when working with the docs but also when working with the software. Actually, almost modern projects are based on git, and tools like dokuwiki which are not tend to fade away from the software scene. 

I will start a new discussion "git crash course" and pick some issue there, the first is the history. Until we have worked through this, be aware of a simple fact: Nothing which is committed into git pushed disappears, and it's actually easy to retrieve older  versions.
