### ISSUE TITLE
Resources - Consider pages for removal

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/development#31]
https://opencpn-manuals.github.io/development/ocpn-dev-manual/5.3.1/codacy.html

https://opencpn-manuals.github.io/development/ocpn-dev-manual/5.3.1/testquality.html

@leamas and @Rasbats

**Comment by Rasbats** [comment]
Perhaps leave under 'Advanced Tools'.

**Comment by leamas** [comment]
I think we should drop it. We should not be tempted to include various things out there which actually are not in use in the project. And, as far I know (not that much, actually) these tools are not used. In particular, we have no automated tests whatsoever. This is actually the bigger issue here...

Static analyze is great, but then we should have actual  build setup etc. which supports it. Without it, it's just a tool out there, we shouldn't document it.

What we *should* do is to file a bug against the plugin templates  and/or the openCPN core about the need for static code analyze tools setup. Once this is implemented, we have something to document.

Just my 5 öre.

**Comment by leamas** [comment]
@rgleason : Saw your commit basically marking these for removal by patching nav.adoc. 

Personally, I don't think we need any more intermediary steps. Since we have agreed on to actually remove them (?),  this is IMHO the time to actually do it.

**Comment by leamas** [comment]
@gleason: Please disregard above, It was the right comment, but in wrong issue. Sorry.

**Comment by leamas** [comment]
@Rasbats:  Thoughts?

**Comment by oplaydo** [comment]
Keep it simple.

**Comment by leamas** [comment]
OK, I'll remove these as well

**Comment by leamas** [comment]
Done. Closing
