### ISSUE TITLE
Resources  - 2 Files Question

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/development#32]
I happened to see these files. They stand alone and are different. Don't know why?
But they look good but the other pages are missing.
https://opencpn-manuals.github.io/development/ocpn-dev-manual/5.3.1/res-online-tools.html
https://opencpn-manuals.github.io/development/ocpn-dev-manual/5.3.1/res-prebuilt-build-files.html

**Comment by leamas** [comment]
The first, on-line tools is linked from the navbar. IMHO, this is sufficient in this case.

As for for the prebuilt files, it might make sense to link to it from the plugins development overview. Will look into it.
