### ISSUE TITLE
Old outdated hardware: consider for removal.

### ISSUE THREAD

**Issue by leamas** [opencpn-manuals/development#33]
@Rasbats  @rgleason : 

We have the following files which refers to outdated hardware and/or outdated build instructions:

  - [building_and_installing_on_cubieboard_2_with_hw_acceleration.adoc](https://opencpn-manuals.github.io/development/ocpn-dev-manual/5.3.1/building_and_installing_on_cubieboard_2_with_hw_acceleration.html)
  - [compiling_on_slackware.adoc](https://opencpn-manuals.github.io/development/ocpn-dev-manual/5.3.1/compiling_on_slackware.html)  (we do not support slackware)
  - [building_on_motorola_xoom.adoc](https://opencpn-manuals.github.io/development/ocpn-dev-manual/5.3.1/building_on_motorola_xoom.html)

I think we should drop. Thoughts?

**Comment by oplaydo** [comment]
Best removed. If someone wants to update add later all well and good.

**Comment by leamas** [comment]
Just out of curiosity and really none of my business, but still: who is behind the oplaydo  nickname? Just seen it in the tutorial...

**Comment by oplaydo** [comment]
@Rasbats : I am using this nickname for making PR for dev manuals.

**Comment by leamas** [comment]
OK :)

**Comment by leamas** [comment]
@rgleason : I can do this, but preferably after some feedback from you.

**Comment by rgleason** [comment]
Ok thks

**Comment by leamas** [comment]
OK, I'm on it.

**Comment by leamas** [comment]
Fixed in ab585589, 395fab9a and d7dd342e, Closing
