### ISSUE TITLE
 Add documentation about CMAKE Env Variables for Devs #60 

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/development#5]
https://github.com/OpenCPN/OpenCPN/issues/2213#issuecomment-826796724

**Comment by leamas** [comment]
Isn't this already covered in https://opencpn-manuals.github.io/development/ocpn-dev-manual/5.3.1/od-compile-cmake.html#_explicit_target_specificationocpn_target_tuple  ? Close bug?

**Comment by leamas** [comment]
No, it's not. A new page on plugin compatibility is needed, added in #5.  OK to close with this?
