### ISSUE TITLE
 Keep Descriptive titles short for Android - Need some instructions about this. #62 

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/development#6]
https://github.com/OpenCPN/OpenCPN/issues/1812

**Comment by leamas** [comment]
Ack, and not only for android. We need to enhance this somehow.

**Comment by leamas** [comment]
I have added https://github.com/leamas/ocpn-pi-docs/commit/4b8af708d7ffa40bc04c2808566c702706a6b928. OK to close with this?

**Comment by rgleason** [comment]
Looks good.
