### ISSUE TITLE
 Add user note about uninstall PI before uninstall O #63 

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/development#7]
https://github.com/OpenCPN/OpenCPN/issues/1539#issuecomment-829127022

**Comment by leamas** [comment]
Isn't a user note by definition something for the User Manual?

**Comment by rgleason** [comment]
Shouldn't there be a note in the plugin manual too?  I need to kewp this reminder somewhere

**Comment by leamas** [comment]
I actually don't think so. Here is a huge risk that we will start writing everything everywhere and create something we can't maintain. At most, we could add a link to the user manual once it's updated with this info. But then again, we need that link to be stable...

**Comment by rgleason** [comment]
Ok, understood. 
Made the changes in wiki here
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:plugins:install_and_enable

Closing
