### ISSUE TITLE
 Use of getPluginDataDir and GetpPrivateApplicationDataLocation() function #64 

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/development#8]
https://github.com/rgleason/LogbookKonni_pi/issues/6#issuecomment-830840789

and

https://github.com/OpenCPN/OpenCPN/issues/2256#issuecomment-831102613

**Comment by leamas** [comment]
Isn't this a duplicate of #23?

**Comment by rgleason** [comment]
Yes, the links are more detailed discussion and some work that could be used.
But closing.

**Comment by leamas** [comment]
You didn't, but I do :)
